sample: Developer Finder
githubOrg: TylerLu
githubRepo: Developer-Finder
markdown: kramdown
highlighter: rouge
gems:
    - jekyll-gist
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: Todd Baginski
      author_github: tbag
keep_files: ['app_data/jobs/triggered','app_data/jobs/continuous']
baseurl: /Developer-Finder
